name: Hello World CI

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello message
        run: echo "Hello from Miras"

      - name: Show operating system
        run: uname -a
